force-app/main/default/objects/Case/fields/Booking_number_from_webform__c.field-meta.xml
<CustomField>
    <fullName>Booking_number_from_webform__c</fullName>
    <inlineHelpText>Provide booking number in format of &quot;PO# 00000000&quot;</inlineHelpText>
    <label>Booking number from webform</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Last_Change_Org_Id__c.field-meta.xml
<CustomField>
    <fullName>Last_Change_Org_Id__c</fullName>
    <label>Last Change Org Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Last_status_change_date__c.field-meta.xml
<CustomField>
    <fullName>Last_status_change_date__c</fullName>
    <label>Last status change date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Preferred_language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_language__c</fullName>
    <label>Preferred language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>--None--</fullName>
                <isActive>false</isActive>
                <label>--None--</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/previous_closed_total_time__c.field-meta.xml
<CustomField>
    <fullName>previous_closed_total_time__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Previous Closed total time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Recent_close_time__c.field-meta.xml
<CustomField>
    <fullName>Recent_close_time__c</fullName>
    <formula>ROUND((NOW() - ClosedDate)*24*60, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Recent close time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Related_booking__c.field-meta.xml
<CustomField>
    <fullName>Related_booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking related</label>
    <referenceTo>Schedule_booking__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Times_reopened__c.field-meta.xml
<CustomField>
    <fullName>Times_reopened__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Times reopened</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Schedule_booking__c/Schedule_booking__c.object-meta.xml
<CustomObject>
    <label>Schedule booking</label>
    <nameField>
        <displayFormat>PO# {00000000}</displayFormat>
        <label>Schedule booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_booking__c/fields/Booking_name__c.field-meta.xml
<CustomField>
    <fullName>Booking_name__c</fullName>
    <displayFormat>PO# {00000000}</displayFormat>
    <label>Booking name</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/CaseTriggerHelper.cls
public with sharing class CaseTriggerHelper {

    private static final String MY_LAST_CHANGE_ORG_NAME = 'FILIP';

    public void getQueueForCase(Case newCase) {
        if (newCase.OwnerId.getSobjectType() != User.getSObjectType()) {
            Id queueLanguageId = CaseRoutingService.getInstance().getQueueForCase(newCase);
            if (queueLanguageId != null) {
                newCase.OwnerId = queueLanguageId;
                if (newCase.External_Id__c == null) {
                    newCase.External_Id__c = GuidGenerator.generate();
                }
            }
        }

    }

    public void getDefaultQueue(Case newCase, Case oldCase) {
        if (oldCase.Preferred_language__c != newCase.Preferred_language__c) {
            newCase.OwnerId = CaseRoutingService.getInstance().getDefaultQueue(oldCase.OwnerId, LanguageEnum.valueOf(oldCase.Preferred_language__c));
        }

    }

    public void incrementTimesOpenedField(Case newCase, Case oldCase) {
        if (oldCase.Status == 'Closed' && oldCase.Status != newCase.Status) {
            if (newCase.Times_reopened__c != null) {
                newCase.Times_reopened__c += 1;
            } else {
                newCase.Times_reopened__c = 1;
            }
        }
    }

    public void setDateTimeOfLastStatusChange(Case newCase, Case oldCase) {
        if (oldCase.Status != newCase.Status) {
            newCase.Last_status_change_date__c = Datetime.now();
        }
    }

    public void setDateTimeOfLastStatusChange(Case newCase) {
        newCase.Last_status_change_date__c = Datetime.now();
    }

    public void calculatePreviousCloseTimes(Case newCase, Case oldCase) {
        String statusIndicatingClosed = 'Closed';
        if (oldCase.Status == statusIndicatingClosed && newCase.Status != statusIndicatingClosed) {
            newCase.previous_closed_total_time__c = newCase.previous_closed_total_time__c += oldCase.Recent_close_time__c;
        }
    }

    public void assignRelatedBooking(Case newCase) {
        // if case. bookingNumber != null {
        List<String> bookingNumber = new List<String>();
        Map<String, Id> bookingsNamesAndIds = new Map<String, Id>();
        bookingNumber.add(newCase.Booking_number_from_webform__c);
        // bulk bef
        List<Schedule_booking__c> bookings = new List<Schedule_booking__c>([SELECT Booking_name__c, Id FROM Schedule_booking__c WHERE Booking_name__c in :bookingNumber]);
        for (Schedule_booking__c booking : bookings) {
            bookingsNamesAndIds.put(booking.Booking_name__c, booking.Id);
        }
        newCase.Related_booking__c = bookingsNamesAndIds.get (newCase.Booking_number_from_webform__c);
    }

    public void setLastChangeOrgOnCaseUponUpdate(Case newCase, Case oldCase) {
        if (newCase.Preferred_language__c != oldCase.Preferred_language__c ||
                newCase.RecordType.DeveloperName != oldCase.RecordType.DeveloperName ||
                newCase.Priority != oldCase.Priority ||
                newCase.Origin != oldCase.Priority ||
                newCase.Subject != oldCase.Subject ||
                newCase.Description != oldCase.Description ||
                newCase.Comments != oldCase.Comments ||
                newCase.SuppliedPhone != oldCase.SuppliedPhone ||
                newCase.SuppliedEmail != oldCase.SuppliedEmail ||
                newCase.SuppliedName != oldCase.SuppliedName) {
            if (RestUtilities.isRestApiContext() == false) {
                newCase.Last_Change_Org_Id__c = MY_LAST_CHANGE_ORG_NAME;
            }
        }
    }

    public void setLastChangeOrgUponInsert(Case newCase) {
        if (String.isBlank(newCase.Last_Change_Org_Id__c)) {
            newCase.Last_Change_Org_Id__c = MY_LAST_CHANGE_ORG_NAME;
        }
    }

}