force-app/main/default/objects/Case/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Preferred_language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_language__c</fullName>
    <label>Preferred language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>--None--</fullName>
                <isActive>false</isActive>
                <label>--None--</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseWrapper.cls
/**
 * Created by POTERFI on 3/16/2022.
 */

public with sharing class CaseWrapper {

    public CaseWrapper (Case caseRecord){
        this.external_id = caseRecord.External_Id__c;
        this.preferred_language = caseRecord.Preferred_Language__c;
        this.record_type = caseRecord.RecordType.DeveloperName;
        this.priority=caseRecord.Priority;
        this.origin=caseRecord.Origin;
        this.subject=caseRecord.Subject;
        this.description=caseRecord.Description;
        this.comments=caseRecord.Comments;
        this.suppliedEmail=caseRecord.SuppliedEmail;
        this.suppliedPhone=caseRecord.SuppliedPhone;
        this.suppliedName=caseRecord.SuppliedName;
    }

    public String external_id {get; set;}
    public String preferred_language {get; set;}
    public String record_type{get; set;}
    public String priority {get; set;}
    public String origin {get; set;}
    public String subject {get; set;}
    public String description {get; set;}
    public String comments {get; set;}
    public String suppliedEmail {get; set;}
    public String suppliedPhone {get; set;}
    public String suppliedName {get; set;}
}