force-app/main/default/objects/Case/fields/Preferred_language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_language__c</fullName>
    <label>Preferred language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>--None--</fullName>
                <isActive>false</isActive>
                <label>--None--</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Routing_Configuration__mdt/fields/Queue_Dispatcher__c.field-meta.xml
<CustomField>
    <fullName>Queue_Dispatcher__c</fullName>
    <label>Queue Dispatcher</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Routing_Configuration__mdt/fields/Routing_Chinese__c.field-meta.xml
<CustomField>
    <fullName>Routing_Chinese__c</fullName>
    <label>Routing Chinese</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Routing_Configuration__mdt/fields/Routing_English__c.field-meta.xml
<CustomField>
    <fullName>Routing_English__c</fullName>
    <label>Routing English</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Routing_Configuration__mdt/fields/Routing_French__c.field-meta.xml
<CustomField>
    <fullName>Routing_French__c</fullName>
    <label>Routing French</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Routing_Configuration__mdt/fields/Routing_German__c.field-meta.xml
<CustomField>
    <fullName>Routing_German__c</fullName>
    <label>Routing German</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Routing_Configuration__mdt/fields/Routing_Italian__c.field-meta.xml
<CustomField>
    <fullName>Routing_Italian__c</fullName>
    <label>Routing Italian</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Routing_Configuration__mdt/fields/Routing_Portuguese__c.field-meta.xml
<CustomField>
    <fullName>Routing_Portuguese__c</fullName>
    <label>Routing Portuguese</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseRoutingService.cls
public with sharing class CaseRoutingService {
    
    private static final Map<LanguageEnum, SObjectField> languageToQueueMap = new Map<LanguageEnum,SObjectField>{
        	LanguageEnum.English => Routing_Configuration__mdt.Routing_English__c,
            LanguageEnum.German => Routing_Configuration__mdt.Routing_German__c,
            LanguageEnum.Chinese => Routing_Configuration__mdt.Routing_Chinese__c,
            LanguageEnum.French => Routing_Configuration__mdt.Routing_French__c,
            LanguageEnum.Italian => Routing_Configuration__mdt.Routing_Italian__c,
            LanguageEnum.Portuguese => Routing_Configuration__mdt.Routing_Portuguese__c
    };

    private static CaseRoutingService instance;
    private static Map <String, Group> queueByDeveloperName;
    private static Map <Id, Group> queue;

    public String getQueueDispatcherName(Id languageBasedQueueName, LanguageEnum queueLanguage){
        String languageBasedQueueNameToString = queue.get(languageBasedQueueName).DeveloperName;
        System.debug(languageBasedQueueNameToString);


        for (Routing_Configuration__mdt routing : CaseRoutingConfiguration.getInstance().getAllRoutingConfig()) {
            SObjectField routingFieldBasedOnLanguage = languageToQueueMap.get(queueLanguage);
            System.debug(routingFieldBasedOnLanguage);
            if (routingFieldBasedOnLanguage != null && routing.get(routingFieldBasedOnLanguage) == languageBasedQueueNameToString) {
                return routing.Queue_Dispatcher__c;
            }
        }
        return null;
    }

    public Id getDefaultQueue(String languageBasedQueueName, LanguageEnum queueLanguage){
        String routing = getQueueDispatcherName(languageBasedQueueName, queueLanguage);
        Group defaultQueue = queueByDeveloperName.get(routing);
        return defaultQueue != null ? defaultQueue.Id : null;
    }
    
    public Id getQueueForCase(Case incomingCase){    
        if (!queue.containsKey((String) incomingCase.OwnerId)){
            System.debug('incomingCase Owner id is null');
        return null;
        }
        
       Routing_Configuration__mdt metadataConfig = CaseRoutingConfiguration.getInstance().getRoutingData(queue.get(incomingCase.OwnerId).DeveloperName);
        
        if (!(metadataConfig == null)){
            SObjectField languageToGet = languageToQueueMap.get(LanguageEnum.valueOf(incomingCase.Preferred_Language__c));
            String routing = (String) metadataConfig.get(languageToGet);
            Group routedQueue = queueByDeveloperName.get(routing);
            return routedQueue != null ? routedQueue.Id : null;
        }
        return null;
    }

    public static CaseRoutingService getInstance(){
        if(instance == null){
           instance = new CaseRoutingService();
        }
        return instance;
    }

    private CaseRoutingService(){
        queueByDeveloperName = new Map <String,Group>();
        queue = new Map <Id, Group>([SELECT Id, DeveloperName from GROUP where Type = 'Queue']);
        for (Group queue : queue.values()){
            queueByDeveloperName.put(queue.DeveloperName, queue);
        }
    }
}