force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/Port_of_Destination__c.field-meta.xml
<CustomField>
    <fullName>Port_of_Destination__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of Destination</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Port</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Routes (Port of Destination)</relationshipLabel>
    <relationshipName>Routes_end</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/Port_of_Origin__c.field-meta.xml
<CustomField>
    <fullName>Port_of_Origin__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of Origin</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Port</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes_start</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Schedule</label>
    <nameField>
        <label>Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Arrival_date__c.field-meta.xml
<CustomField>
    <fullName>Arrival_date__c</fullName>
    <label>Arrival date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Departure_date__c.field-meta.xml
<CustomField>
    <fullName>Departure_date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Departure date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>schedule_route</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Schedule_Status__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Status__c</fullName>
    <formula>IF( AND(Departure_date__c  &lt;  TODAY(),  Arrival_date__c &gt; TODAY()), &apos;In transit&apos;,  IF( Departure_date__c &gt; TODAY(), &apos;Before Transit&apos; ,  IF(  Arrival_date__c &lt; TODAY(), &apos;Docked&apos;, &apos;After departure&apos;) ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Schedule Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vessel</label>
    <referenceTo>Vessel__c</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vessel__c/Vessel__c.object-meta.xml
<CustomObject>
    <label>Vessel</label>
    <nameField>
        <label>Ship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessels</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/FindSchedules.cls
/**
 * Created by POTERFI on 2/7/2022.
 */

public with sharing class FindSchedules {

    @AuraEnabled
    public static List<ScheduleWrapper> getSchedules(Date startDate, Date endDate, String departure, String arrival) {

        StringQueryBuilder stringQueryBuilder = new StringQueryBuilder();

        String query = stringQueryBuilder
                .addField('Id')
                .addField('Name')
                .addField('Route__r.Name')
                .addField('Vessel__r.Name')
                .addField('Departure_date__c')
                .addField('Arrival_date__c')
                .addField('Route__r.Port_of_Origin__c')
                .addField('Route__r.Port_of_Destination__c')
                .fromx('Schedule__c')
                .addWhere('Departure_date__c', startDate, '=' )
                .addWhere('Arrival_date__c', endDate, '=')
                .addWhere('Route__r.Port_of_Origin__c', departure, '=')
                .addWhere('Route__r.Port_of_Destination__c', arrival, '=')
                .addWhere('Schedule_Status__c', 'Before Transit', '=')
                .build();
        System.debug(query);

        List<Schedule__c> schedules = stringQueryBuilder.query();

        List<ScheduleWrapper> wrappedSchedules = FindSchedules.getRelatedObjectsNames(schedules);
        return wrappedSchedules;

    }


    public static List<ScheduleWrapper> getRelatedObjectsNames(List<Schedule__c> scheds) {
        System.debug(scheds);


        List<ScheduleWrapper> wrappedSchedules = new List<ScheduleWrapper>();

        System.debug(scheds);
        for (Schedule__c schedule : scheds) {

            ScheduleWrapper wrapper = new ScheduleWrapper();
            wrapper.id = schedule.Id;
            wrapper.scheduleName = schedule.Name;
            wrapper.scheduleStartDate = schedule.Departure_date__c;
            wrapper.scheduleEndDate = schedule.Arrival_date__c;
            wrapper.routeName = schedule.Route__r.Name;
            wrapper.vesselName = schedule.Vessel__r.Name;
            wrappedSchedules.add(wrapper);

        }
        System.debug(wrappedSchedules);
        return wrappedSchedules;

    }

}