force-app/main/default/objects/Opportunity/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <summarizedField>Schedule_booking__c.Amount__c</summarizedField>
    <summaryForeignKey>Schedule_booking__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Declared_TEU__c.field-meta.xml
<CustomField>
    <fullName>Declared_TEU__c</fullName>
    <description>Sum of declared TEUs on related bookings</description>
    <label>Declared TEU</label>
    <summarizedField>Schedule_booking__c.Declared_Teu__c</summarizedField>
    <summaryForeignKey>Schedule_booking__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunity_schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Schedule</label>
    <nameField>
        <label>Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Amount_in_Booked_Status__c.field-meta.xml
<CustomField>
    <fullName>Amount_in_Booked_Status__c</fullName>
    <label>Amount in Booked Status</label>
    <summarizedField>Schedule_booking__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Schedule_booking__c.Status__c</field>
        <operation>equals</operation>
        <value>Booked</value>
    </summaryFilterItems>
    <summaryForeignKey>Schedule_booking__c.Schedule__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Amount_in_Locked_Status__c.field-meta.xml
<CustomField>
    <fullName>Amount_in_Locked_Status__c</fullName>
    <label>Amount in Locked Status</label>
    <summarizedField>Schedule_booking__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Schedule_booking__c.Status__c</field>
        <operation>equals</operation>
        <value>Locked</value>
    </summaryFilterItems>
    <summaryForeignKey>Schedule_booking__c.Schedule__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Amount_in_New_Status__c.field-meta.xml
<CustomField>
    <fullName>Amount_in_New_Status__c</fullName>
    <label>Amount in New Status</label>
    <summarizedField>Schedule_booking__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Schedule_booking__c.Status__c</field>
        <operation>equals</operation>
        <value>New</value>
    </summaryFilterItems>
    <summaryForeignKey>Schedule_booking__c.Schedule__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/TEU_booked_on_Booked_status__c.field-meta.xml
<CustomField>
    <fullName>TEU_booked_on_Booked_status__c</fullName>
    <label>TEU booked on Booked status</label>
    <summarizedField>Schedule_booking__c.Declared_Teu__c</summarizedField>
    <summaryFilterItems>
        <field>Schedule_booking__c.Status__c</field>
        <operation>equals</operation>
        <value>Booked</value>
    </summaryFilterItems>
    <summaryForeignKey>Schedule_booking__c.Schedule__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/TEU_booked_on_Locked_Status__c.field-meta.xml
<CustomField>
    <fullName>TEU_booked_on_Locked_Status__c</fullName>
    <label>TEU booked on Locked Status</label>
    <summarizedField>Schedule_booking__c.Declared_Teu__c</summarizedField>
    <summaryFilterItems>
        <field>Schedule_booking__c.Status__c</field>
        <operation>equals</operation>
        <value>Locked</value>
    </summaryFilterItems>
    <summaryForeignKey>Schedule_booking__c.Schedule__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/TEU_booked_on_New_Status__c.field-meta.xml
<CustomField>
    <fullName>TEU_booked_on_New_Status__c</fullName>
    <label>TEU booked on New Status</label>
    <summarizedField>Schedule_booking__c.Declared_Teu__c</summarizedField>
    <summaryFilterItems>
        <field>Schedule_booking__c.Status__c</field>
        <operation>equals</operation>
        <value>New</value>
    </summaryFilterItems>
    <summaryForeignKey>Schedule_booking__c.Schedule__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Schedule_booking__c/Schedule_booking__c.object-meta.xml
<CustomObject>
    <label>Schedule booking</label>
    <nameField>
        <displayFormat>PO# {00000000}</displayFormat>
        <label>Schedule booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_booking__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schedule_booking__c/fields/Declared_Teu__c.field-meta.xml
<CustomField>
    <fullName>Declared_Teu__c</fullName>
    <label>Declared Teu</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Schedule_booking__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>schedule bookings</relationshipLabel>
    <relationshipName>schedule_bookings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule_booking__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>schedule bookings</relationshipLabel>
    <relationshipName>schedule_bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule_booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ScheduleBookingService.cls
/**
 * Created by POTERFI on 2/15/2022.
 */

public with sharing class ScheduleBookingService {

    /*

    public List<Id> getAffectedOpportunitiesIds(List<Schedule_booking__c> bookingsProcessed) {
        List<Id> opportunitiesToUpdateIds = new List<Id>();

        for (Schedule_booking__c booking : bookingsProcessed) {
            opportunitiesToUpdateIds.add(booking.Opportunity__c);
        }
        return opportunitiesToUpdateIds;
    }

    public List<Opportunity> getListOfOpportunities(List<Id> affectedOpportunitiesIds) {
        List<Opportunity> opportunitiesToUpdate = [SELECT Id, Name, Amount__c FROM Opportunity WHERE Id = :affectedOpportunitiesIds];
        return opportunitiesToUpdate;
    }

    public List<Opportunity> updateOpportunityAmount(List<Opportunity> opportunitiesToUpdate, List<Schedule_booking__c> bookingsProcessed) {
        Map<String, Decimal> oldBookingValues = new Map<String, Decimal>();
        List<Schedule_booking__c> oldBookings = new List<Schedule_booking__c>();

        if (Trigger.isUpdate) {
            oldBookings = Trigger.old;
            for (Schedule_booking__c oldBooking : oldBookings) {
                if (oldBooking.Amount__c == null) {
                    oldBookingValues.put(oldBooking.Name, 0);
                } else {
                    oldBookingValues.put(oldBooking.Name, oldBooking.Amount__c);
                }
            }
        }


        for (Opportunity opportunity : opportunitiesToUpdate) {
            for (Schedule_booking__c booking : bookingsProcessed) {
                if (opportunity.Id == booking.Opportunity__c) {
                    if (Trigger.isInsert) {
                        opportunity.Amount__c += booking.Amount__c;
                    } else if (Trigger.isUpdate) {
                        Decimal difference = getZeroIfNull(booking.Amount__c) - getZeroIfNull(oldBookingValues.get(booking.Name));
                        // Decimal difference = booking.Amount__c - oldBookingValues.get(booking.Name);
                        opportunity.Amount__c = getZeroIfNull(opportunity.Amount__c) + getZeroIfNull(difference);
                    }
                }
            }
        }

        return opportunitiesToUpdate;
    }

    public List<Schedule__c> getAffectedSchedules(List<Id> relatedSchedulesId) {
        List<Schedule__c> schedules = [SELECT Id, Name, TEU_booked_on_New_Status__c, TEU_booked_on_Locked_Status__c, TEU_booked_on_Booked_status__c, Amount_in_Booked_Status__c, Amount_in_Locked_Status__c, Amount_in_New_Status__c FROM Schedule__c WHERE Id = :relatedSchedulesId];
        return schedules;
    }

    public List<Id> getSchedulesIds(List<Schedule_booking__c> bookingsProcessed) {
        List<Id> relatedSchedulesIds = new List<Id>();
        for (Schedule_booking__c booking : bookingsProcessed) {
            relatedSchedulesIds.add(booking.Schedule__c);
        }
        return relatedSchedulesIds;
    }

    public List<Decimal> getTeuAndAmountNumberInNewStatus(List<Schedule_booking__c> bookingsProcessed) {
        Decimal totalTEU = 0;
        List<Id> relatedSchedulesIds = getSchedulesIds(bookingsProcessed);
        List<Schedule_booking__c> bookings = [SELECT Id, Name, Declared_Teu__c, Schedule__c, Amount__c FROM Schedule_booking__c WHERE Status__c = 'New' AND Schedule__c = :relatedSchedulesIds];
        Decimal totalAmount = 0;

        for (Schedule_booking__c booking : bookings) {
            totalTEU += booking.Declared_Teu__c;
            totalAmount += booking.Amount__c;
        }
        List<Decimal> teusAndAmount = new List<Decimal>{
                totalTEU, totalAmount
        };
        return teusAndAmount;
    }

    public List<Decimal> getTeuAndAmountNumberInLockedStatus(List<Schedule_booking__c> bookingsProcessed) {
        Decimal totalTEU = 0;
        List<Id> relatedSchedulesIds = getSchedulesIds(bookingsProcessed);
        List<Schedule_booking__c> bookings = [SELECT Id, Name, Declared_Teu__c, Schedule__c, Amount__c FROM Schedule_booking__c WHERE Status__c = 'Locked' AND Schedule__c = :relatedSchedulesIds];
        Decimal totalAmount = 0;

        for (Schedule_booking__c booking : bookings) {
            totalTEU += booking.Declared_Teu__c;
            totalAmount += booking.Amount__c;
        }
        List<Decimal> teusAndAmount = new List<Decimal>{
                totalTEU, totalAmount
        };
        return teusAndAmount;
    }

    public List<Decimal> getTeuAndAmountNumberInBookedStatus(List<Schedule_booking__c> bookingsProcessed) {
        Decimal totalTEU = 0;
        List<Id> relatedSchedulesIds = getSchedulesIds(bookingsProcessed);
        List<Schedule_booking__c> bookings = [SELECT Id, Name, Declared_Teu__c, Schedule__c, Amount__c FROM Schedule_booking__c WHERE Status__c = 'Booked' AND Schedule__c = :relatedSchedulesIds];
        Decimal totalAmount = 0;

        for (Schedule_booking__c booking : bookings) {
            totalTEU += booking.Declared_Teu__c;
            totalAmount += booking.Amount__c;
        }
        List<Decimal> teusAndAmount = new List<Decimal>{
                totalTEU, totalAmount
        };

        return teusAndAmount;
    }

    public List<Schedule__c> returnUpdatedSchedules(List<Schedule_booking__c> bookingsProcessed) {
        List<Decimal> newTEU = getTeuAndAmountNumberInNewStatus(bookingsProcessed);
        List<Decimal> lockedTEU = getTeuAndAmountNumberInLockedStatus(bookingsProcessed);
        List<Decimal> bookedTEU = getTeuAndAmountNumberInBookedStatus(bookingsProcessed);

        List<Schedule__c> schedules = getAffectedSchedules(getSchedulesIds(bookingsProcessed));

        for (Schedule__c schedule : schedules) {
            schedule.TEU_booked_on_New_Status__c = newTEU[0];
            schedule.Amount_in_New_Status__c = newTEU[1];

            schedule.TEU_booked_on_Locked_Status__c = lockedTEU[0];
            schedule.Amount_in_Locked_Status__c = lockedTEU[1];

            schedule.TEU_booked_on_Booked_status__c = bookedTEU[0];
            schedule.Amount_in_Booked_Status__c = bookedTEU[1];
        }
        return schedules;
    }

    private Decimal getZeroIfNull(Decimal num){
        return num == null ? 0 : num;
    }

*/
}