force-app/main/default/objects/Routing_Configuration__mdt/fields/Queue_Dispatcher__c.field-meta.xml
<CustomField>
    <fullName>Queue_Dispatcher__c</fullName>
    <label>Queue Dispatcher</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseRoutingConfigurationTest.cls
@IsTest
private class CaseRoutingConfigurationTest{

    @IsTest static void shouldGetCorrectConfigurationGivenExitingQueueDispatcher(){
        String queueDispatcherName = 'Payment_Dept';
        Routing_Configuration__mdt expectedRouting = [
                SELECT Id
                FROM Routing_Configuration__mdt
                WHERE Queue_Dispatcher__c = :queueDispatcherName
        ];
        Routing_Configuration__mdt routing = CaseRoutingConfiguration.getInstance().getRoutingData(queueDispatcherName);
        System.assertEquals(expectedRouting.Id, routing.Id);
    }

    @IsTest static void shouldReturnNullGivenNotExitingQueueDispatcher(){
        Routing_Configuration__mdt routing = CaseRoutingConfiguration.getInstance().getRoutingData('Polish_Payment_Dept');
        System.assertEquals(null, routing);
    }
}